<a href="https://colab.research.google.com/github/yogaaditandanu/BelajarDeepLearning/blob/main/Time_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import tensorflow as tf
df = pd.read_csv('https://drive.google.com/uc?id=15RfMD9lNkpS3cVN7j3_dsJKZ8_5RJG5z')
df.head()

date   meantemp   humidity  wind_speed  meanpressure
0  2013-01-01  10.000000  84.500000    0.000000   1015.666667
1  2013-01-02   7.400000  92.000000    2.980000   1017.800000
2  2013-01-03   7.166667  87.000000    4.633333   1018.666667
3  2013-01-04   8.666667  71.333333    1.233333   1017.166667
4  2013-01-05   6.000000  86.833333    3.700000   1016.500000

In [2]:
def windowed_dataset(series, window_size, batch_size, shuffle_buffer): #definisi fungsi yg menerima 4 parameter,
#series : data deret waktu, window_size = ukuran jendela yg akan digunakan, batch size = ukuran batch, shuffle buffer = ukuran utk pengacakan
    series = tf.expand_dims(series, axis=-1) #mengubah dimensi series dgn menambahkan 1 dimensi baru di posisi terakhir
    ds = tf.data.Dataset.from_tensor_slices(series) #membuat dataset TF menjadi sebuah series
    ds = ds.window(window_size + 1, shift=1, drop_remainder=True) #membagi dataset menjadi jendela berukuran window_size+1 dgn jarak 1 antara jendela tsb
    ds = ds.flat_map(lambda w: w.batch(window_size + 1)) #mengubah setiap window menjadi sebuah batch dgn ukuran window_size+1
    ds = ds.shuffle(shuffle_buffer) #mengacak dataset dgn menggunakan buffer ukuran shuffle_buffer
    ds = ds.map(lambda w: (w[:-1], w[-1:])) #memetakan setiap batch menjadi sepasang data input & target
    return ds.batch(batch_size).prefetch(1) #mengelompokkan batch dataset menjadi batch dgn ukuran batch size

In [3]:
dates = df['date'].values
temp = df['meantemp'].values

Kode di atas akan mengambil seluruh data dari dataset yang sebelumnya sudah kita siapkan.

In [6]:
train_set = windowed_dataset(temp, window_size=2, batch_size=3, shuffle_buffer=1000)

In [7]:
for data in train_set:
  print(data)
  break

(<tf.Tensor: shape=(3, 2, 1), dtype=float64, numpy=
array([[[36.   ],
        [37.75 ]],

       [[28.25 ],
        [32.125]],

       [[18.375],
        [18.625]]])>, <tf.Tensor: shape=(3, 1, 1), dtype=float64, numpy=
array([[[35.25]],

       [[29.2 ]],

       [[18.25]]])>)
